/**
 * Read-only inspector for the agents table.
 *
 * Reports counts that drive the enrichment + invite plan:
 *  - total agents
 *  - already invited (auth_user_id set) vs not
 *  - email field state: missing, looks placeholder, looks real
 *  - which enrichment sources are reachable (website / instagram / facebook)
 *
 * No writes. Safe to run any time.
 *
 *   pnpm tsx scripts/inspect-agents.ts
 */

import { config as loadEnv } from 'dotenv';
import { existsSync } from 'fs';
import { join } from 'path';
for (const file of ['.env.local', '.env']) {
  const p = join(process.cwd(), file);
  if (existsSync(p)) loadEnv({ path: p });
}

import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL =
  process.env.NEXT_PUBLIC_SUPABASE_URL ||
  process.env.SUPABASE_URL ||
  process.env.SUPABASE_PROJECT_URL;
const SERVICE_KEY =
  process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_SERVICE_KEY;

if (!SUPABASE_URL || !SERVICE_KEY) {
  console.error('Missing SUPABASE_URL and/or SUPABASE_SERVICE_ROLE_KEY.');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SERVICE_KEY, {
  auth: { autoRefreshToken: false, persistSession: false },
});

type AgentLite = {
  id: string;
  auth_user_id: string | null;
  name: string | null;
  known_as: string | null;
  city: string | null;
  country: string | null;
  email_id: string | null;
  email_isVerified: string | null;
  contact_number: string | null;
  whatsapp_url: string | null;
  instagram_url: string | null;
  facebook_url: string | null;
  about_us: string | null;
  profile_image: string | null;
};

// Heuristic: an email is "probably placeholder" if it's empty, ends in a
// throwaway domain, or looks autogenerated. We don't auto-act on this — it's
// just to size the problem.
const PLACEHOLDER_DOMAINS = new Set([
  'example.com',
  'example.org',
  'test.com',
  'mailinator.com',
  'noemail.com',
  'placeholder.com',
  'searchumrah.com',
]);

function classifyEmail(email: string | null): 'missing' | 'placeholder' | 'real' {
  if (!email || !email.trim()) return 'missing';
  const e = email.trim().toLowerCase();
  if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(e)) return 'placeholder';
  const domain = e.split('@')[1];
  if (PLACEHOLDER_DOMAINS.has(domain)) return 'placeholder';
  if (/^(noreply|no-reply|test|dummy|fake|temp|sample)@/i.test(e)) return 'placeholder';
  return 'real';
}

function pct(n: number, total: number): string {
  if (!total) return '0%';
  return `${((n / total) * 100).toFixed(1)}%`;
}

async function main() {
  const { data, error, count } = await supabase
    .from('agents')
    .select(
      'id, auth_user_id, name, known_as, city, country, email_id, email_isVerified, contact_number, whatsapp_url, instagram_url, facebook_url, about_us, profile_image',
      { count: 'exact' }
    );

  if (error) {
    console.error('Query failed:', error.message);
    process.exit(1);
  }

  const agents = (data ?? []) as AgentLite[];
  const total = count ?? agents.length;

  const invited = agents.filter((a) => !!a.auth_user_id).length;
  const notInvited = total - invited;
  const verified = agents.filter(
    (a) => a.email_isVerified === 'true' || a.email_isVerified === 'TRUE'
  ).length;

  const emailMissing = agents.filter((a) => classifyEmail(a.email_id) === 'missing').length;
  const emailPlaceholder = agents.filter(
    (a) => classifyEmail(a.email_id) === 'placeholder'
  ).length;
  const emailReal = agents.filter((a) => classifyEmail(a.email_id) === 'real').length;

  const hasInstagram = agents.filter((a) => !!a.instagram_url?.trim()).length;
  const hasFacebook = agents.filter((a) => !!a.facebook_url?.trim()).length;
  const hasWhatsapp = agents.filter((a) => !!a.whatsapp_url?.trim()).length;
  const hasPhone = agents.filter((a) => !!a.contact_number?.trim()).length;
  const hasAbout = agents.filter((a) => (a.about_us?.trim().length ?? 0) > 20).length;
  const hasImage = agents.filter((a) => !!a.profile_image?.trim()).length;

  // Any reachable enrichment source means we have *something* to crawl.
  const reachable = agents.filter(
    (a) => a.instagram_url?.trim() || a.facebook_url?.trim() || a.whatsapp_url?.trim()
  ).length;

  console.log('━━━ agents table inspection ━━━');
  console.log(`total agents:                     ${total}`);
  console.log('');
  console.log('— auth / invite state —');
  console.log(`  already invited (auth_user_id): ${invited.toString().padStart(5)} (${pct(invited, total)})`);
  console.log(`  not invited:                    ${notInvited.toString().padStart(5)} (${pct(notInvited, total)})`);
  console.log(`  flagged email_isVerified=true:  ${verified.toString().padStart(5)} (${pct(verified, total)})`);
  console.log('');
  console.log('— email field —');
  console.log(`  looks real:                     ${emailReal.toString().padStart(5)} (${pct(emailReal, total)})`);
  console.log(`  looks placeholder/fake:         ${emailPlaceholder.toString().padStart(5)} (${pct(emailPlaceholder, total)})`);
  console.log(`  missing / empty:                ${emailMissing.toString().padStart(5)} (${pct(emailMissing, total)})`);
  console.log('');
  console.log('— enrichment sources present —');
  console.log(`  instagram_url:                  ${hasInstagram.toString().padStart(5)} (${pct(hasInstagram, total)})`);
  console.log(`  facebook_url:                   ${hasFacebook.toString().padStart(5)} (${pct(hasFacebook, total)})`);
  console.log(`  whatsapp_url:                   ${hasWhatsapp.toString().padStart(5)} (${pct(hasWhatsapp, total)})`);
  console.log(`  contact_number:                 ${hasPhone.toString().padStart(5)} (${pct(hasPhone, total)})`);
  console.log(`  about_us > 20 chars:            ${hasAbout.toString().padStart(5)} (${pct(hasAbout, total)})`);
  console.log(`  profile_image:                  ${hasImage.toString().padStart(5)} (${pct(hasImage, total)})`);
  console.log(`  ≥1 reachable social link:       ${reachable.toString().padStart(5)} (${pct(reachable, total)})`);
  console.log('');
  console.log('— sample (first 5 rows, redacted) —');
  for (const a of agents.slice(0, 5)) {
    console.log(
      `  • ${a.known_as || a.name} | ${a.city || '-'} / ${a.country || '-'} | email=${classifyEmail(a.email_id)} | ig=${a.instagram_url ? 'y' : '-'} fb=${a.facebook_url ? 'y' : '-'} wa=${a.whatsapp_url ? 'y' : '-'} | invited=${a.auth_user_id ? 'y' : '-'}`
    );
  }
  console.log('');
  console.log('— top 10 email domains (for placeholder pattern spotting) —');
  const domainCounts = new Map<string, number>();
  for (const a of agents) {
    if (!a.email_id) continue;
    const domain = a.email_id.toLowerCase().trim().split('@')[1];
    if (!domain) continue;
    domainCounts.set(domain, (domainCounts.get(domain) ?? 0) + 1);
  }
  const topDomains = [...domainCounts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 10);
  for (const [domain, n] of topDomains) {
    console.log(`  ${n.toString().padStart(4)}  ${domain}`);
  }
}

main().catch((err) => {
  console.error('\nInspector failed:', err);
  process.exit(1);
});
