create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null references auth.users(id) on delete cascade,
  agent_id uuid not null references auth.users(id) on delete restrict,
  agent_name text not null,
  package_id uuid references public.packages(id) on delete set null,
  slug text not null,
  guests jsonb not null default '[]'::jsonb,
  sharing integer not null default 1,
  booking_mobile text,
  total_amount numeric(12,2) not null default 0,
  currency text not null default 'INR',
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_bookings_auth_user_id on public.bookings(auth_user_id);
create index if not exists idx_bookings_agent_id on public.bookings(agent_id);
create index if not exists idx_bookings_agent_name on public.bookings(agent_name);
create index if not exists idx_bookings_created_at on public.bookings(created_at desc);

alter table public.bookings enable row level security;

drop policy if exists "Bookings are viewable by owner" on public.bookings;
create policy "Bookings are viewable by owner"
on public.bookings
for select
using (auth.uid() = auth_user_id);

drop policy if exists "Owners can create bookings" on public.bookings;
create policy "Owners can create bookings"
on public.bookings
for insert
with check (auth.uid() = auth_user_id);

drop policy if exists "Agent can view assigned bookings" on public.bookings;
create policy "Agent can view assigned bookings"
on public.bookings
for select
using (auth.uid() = agent_id);

drop policy if exists "Agent can update assigned bookings" on public.bookings;
create policy "Agent can update assigned bookings"
on public.bookings
for update
using (auth.uid() = agent_id)
with check (auth.uid() = agent_id);
